#!/usr/bin/env bash
# Rend invocables par le modèle les skills de Matt qu'appellent les routines, et retire
# du triage la mention d'IA qu'il ferait poser en tête de chaque commentaire.
# À relancer après chaque `npx skills update`. Avec --check, échoue si l'un d'eux
# est redevenu réservé à l'utilisateur ou si la mention est revenue (utilisé par
# agent-guard).
set -euo pipefail
mode=${1:-apply}
for name in triage implement implement-spec improve-codebase-architecture; do
  files=$(grep -rlE "^name:[[:space:]]*${name}[[:space:]]*$" --include=SKILL.md \
          .claude/skills .agents/skills 2>/dev/null || true)
  [ -n "$files" ] || { echo "Skill introuvable : $name"; exit 1; }
  for f in $files; do
    if [ "$mode" = "--check" ]; then
      if grep -qE '^disable-model-invocation:[[:space:]]*true' "$f"; then
        echo "Encore réservé à l'utilisateur : $f"; exit 1
      fi
    else
      sed -i.bak -E 's/^disable-model-invocation:[[:space:]]*true[[:space:]]*$/disable-model-invocation: false/' "$f"
      rm -f "$f.bak"
    fi
  done
done
triage=.claude/skills/triage/SKILL.md
if [ "$mode" = "--check" ]; then
  if grep -q 'generated by AI' "$triage"; then echo "Mention d'IA revenue : $triage"; exit 1; fi
else
  perl -0777 -i -pe 's{Every comment or issue posted to the issue tracker during triage.*?```\n.*?```\n\n}{}s' "$triage"
fi
